pacman::p_load(data.table)
pacman::p_load(caret)
pacman::p_load(magrittr)
pacman::p_load(dplyr)
pacman::p_load(tidyr)
# pacman::p_load(tibble)
# pacman::p_load(snpStats)
# pacman::p_load(broom)
# pacman::p_load_gh('alyssafrazee/RSkittleBrewer')
pacman::p_load(doMC)
pacman::p_load(glmnet)
# pacman::p_load(GenABEL)
# pacman::p_load(GenABEL.data)
pacman::p_load(ggplot2)
pacman::p_load(cowplot)
# pacman::p_load(mlr)
# pacman::p_load(pryr)
# pacman::p_load_gh("YaohuiZeng/biglasso")

# pacman::p_load(gap)
# pacman::p_load(regress)
# pacman::p_load(kinship2)
pacman::p_load(coxme)
pacman::p_load(simulator)
pacman::p_load(gaston)
pacman::p_load_gh('StoreyLab/popkin')
pacman::p_load_gh('StoreyLab/bnpsd') # load this after popkin
pacman::p_load_gh('OchoaLab/simtrait')
# pacman::p_load('lfa')
# pacman::p_load('RColorBrewer')
# pacman::p_load_gh('sahirbhatnagar/ggmix@master')
devtools::load_all(path = "/home/sahir/git_repositories/ggmix/")
# source("/mnt/GREENWOOD_BACKUP/home/sahir.bhatnagar/ggmix/R/fitting.R")
# source("/mnt/GREENWOOD_BACKUP/home/sahir.bhatnagar/ggmix/R/functions.R")
# source("/mnt/GREENWOOD_BACKUP/home/sahir.bhatnagar/ggmix/R/methods.R")
# source("/mnt/GREENWOOD_BACKUP/home/sahir.bhatnagar/ggmix/R/plot.R")
